version: "3"

tasks:
  default:
    desc: Display available tasks
    cmds:
      - task -l
  lint:
    desc: Run MegaLinter
    cmds:
      - mega-linter-runner --flavor go
  gen-gif:
    desc: Run MegaLinter
    cmds:
      - vhs < img/demo.tape
      - vhs < img/demo-speed.tape
      - vhs < img/demo-color.tape
